language: c
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libogg-dev
    - libflac-dev

before_install:
  - export OPAMYES=1
  - opam init
  - opam install -q -y ocamlfind base-bytes
  - eval `opam config env`
  - git clone https://github.com/savonet/ocaml-ogg.git
  - cd ocaml-ogg && git submodule init && git submodule update && ./bootstrap && ./configure && make && sudo make install

script: ./bootstrap && ./configure && make && make -C examples
